FROM python:3.9

WORKDIR /docs

COPY requirements.txt requirements.txt
RUN apt-get clean \
    && apt-get -y update \
    && pip install --upgrade pip  \
    && apt-get -y install python3-dev \
    && apt-get -y install build-essential \
    && pip install -r requirements.txt \
    && rm -rf /var/cache/apk/*

COPY . .
CMD ["mkdocs", "serve"]