site_name: Transpose Documentation
theme:
  name: material
  palette:
    primary: white
  logo: ./assets/logo-black.png
  favicon: ./assets/favicon.png
  features:
    - navigation.tabs
    - navigation.tabs.sticky


nav:
  - Introduction: 'index.md'
  - 'Quick Start': 'quickstart.md'
  - 'Our Data': 'data.md'
  - SQL API:
    - 'sql/overview.md'
    - Getting Started: 'sql/getting-started.md'
    - 'sql/authentication.md'
    - 'sql/parameters.md'
    - 'sql/playground.md'
    - 'sql/pagination.md'
    - AI Query Assistant:
      - Overview: 'sql/assistant/overview.md'
      - 'sql/assistant/generate-queries.md'
      - 'sql/assistant/optimize-queries.md'
      - 'sql/assistant/debug-queries.md'
      - 'sql/assistant/tips-and-tricks.md'
    - 'sql/multichain.md'
    - 'sql/response.md'
    - Options:
        - 'sql/options/stringify.md'
        - 'sql/options/timeout.md'
        - 'sql/options/cancel.md'
    - Ethereum Tables:
      - Settlement:
        - 'sql/tables/ethereum/settlement_layer/accounts.md'
        - 'sql/tables/ethereum/settlement_layer/blocks.md'
        - 'sql/tables/ethereum/settlement_layer/logs.md'
        - 'sql/tables/ethereum/settlement_layer/traces.md'
        - 'sql/tables/ethereum/settlement_layer/transactions.md'
      - Asset:
        - 'sql/tables/ethereum/asset_layer/nfts.md'
        - 'sql/tables/ethereum/asset_layer/collections.md'
        - 'sql/tables/ethereum/asset_layer/nft_owners.md'
        - 'sql/tables/ethereum/asset_layer/nft_transfers.md'
        - 'sql/tables/ethereum/asset_layer/native_token_owners.md'
        - 'sql/tables/ethereum/asset_layer/native_token_transfers.md'
        - 'sql/tables/ethereum/asset_layer/tokens.md'
        - 'sql/tables/ethereum/asset_layer/token_owners.md'
        - 'sql/tables/ethereum/asset_layer/token_transfers.md'
      - Protocol:
        - 'sql/tables/ethereum/protocol_layer/nft_sales.md'
        - 'sql/tables/ethereum/protocol_layer/bridge_events.md'
        - 'sql/tables/ethereum/protocol_layer/dex_liquidity.md'
        - 'sql/tables/ethereum/protocol_layer/dex_pools.md'
        - 'sql/tables/ethereum/protocol_layer/dex_swaps.md'
        - 'sql/tables/ethereum/protocol_layer/token_prices.md'
        - 'sql/tables/ethereum/protocol_layer/contract_labels.md'
        - 'sql/tables/ethereum/protocol_layer/ens_names.md'
        - Tornado Cash:
          - 'sql/tables/ethereum/protocol_layer/tornado_cash_withdrawals.md'
          - 'sql/tables/ethereum/protocol_layer/tornado_cash_deposits.md'
          - 'sql/tables/ethereum/protocol_layer/tornado_cash_pools.md'
    - Polygon Tables:
      - Settlement:
        - 'sql/tables/polygon/settlement_layer/accounts.md'
        - 'sql/tables/polygon/settlement_layer/blocks.md'
        - 'sql/tables/polygon/settlement_layer/logs.md'
        - 'sql/tables/polygon/settlement_layer/transactions.md'
      - Asset:
        - 'sql/tables/polygon/asset_layer/nfts.md'
        - 'sql/tables/polygon/asset_layer/collections.md'
        - 'sql/tables/polygon/asset_layer/nft_owners.md'
        - 'sql/tables/polygon/asset_layer/nft_transfers.md'
        - 'sql/tables/polygon/asset_layer/native_token_owners.md'
        - 'sql/tables/polygon/asset_layer/native_token_transfers.md'
        - 'sql/tables/polygon/asset_layer/tokens.md'
        - 'sql/tables/polygon/asset_layer/token_owners.md'
        - 'sql/tables/polygon/asset_layer/token_transfers.md'
      - Protocol:
        - 'sql/tables/polygon/protocol_layer/nft_sales.md'
        - 'sql/tables/polygon/protocol_layer/dex_liquidity.md'
        - 'sql/tables/polygon/protocol_layer/dex_pools.md'
        - 'sql/tables/polygon/protocol_layer/dex_swaps.md'
        - 'sql/tables/polygon/protocol_layer/token_prices.md'
    - Arbitrum Tables:
      - Settlement:
        - 'sql/tables/arbitrum/settlement_layer/accounts.md'
        - 'sql/tables/arbitrum/settlement_layer/blocks.md'
        - 'sql/tables/arbitrum/settlement_layer/logs.md'
        - 'sql/tables/arbitrum/settlement_layer/traces.md'
        - 'sql/tables/arbitrum/settlement_layer/transactions.md'
      - Asset:
        - 'sql/tables/arbitrum/asset_layer/nfts.md'
        - 'sql/tables/arbitrum/asset_layer/collections.md'
        - 'sql/tables/arbitrum/asset_layer/nft_owners.md'
        - 'sql/tables/arbitrum/asset_layer/nft_transfers.md'
        - 'sql/tables/arbitrum/asset_layer/native_token_owners.md'
        - 'sql/tables/arbitrum/asset_layer/native_token_transfers.md'
        - 'sql/tables/arbitrum/asset_layer/tokens.md'
        - 'sql/tables/arbitrum/asset_layer/token_owners.md'
        - 'sql/tables/arbitrum/asset_layer/token_transfers.md'
      - Protocol:
        - 'sql/tables/arbitrum/protocol_layer/nft_sales.md'
        - 'sql/tables/arbitrum/protocol_layer/token_prices.md'
        - 'sql/tables/arbitrum/protocol_layer/dex_pools.md'
        - 'sql/tables/arbitrum/protocol_layer/dex_swaps.md'
    - Canto Tables:
      - Settlement:
        - 'sql/tables/canto/settlement_layer/accounts.md'
        - 'sql/tables/canto/settlement_layer/blocks.md'
        - 'sql/tables/canto/settlement_layer/logs.md'
        - 'sql/tables/canto/settlement_layer/traces.md'
        - 'sql/tables/canto/settlement_layer/transactions.md'
      - Asset:
        - 'sql/tables/canto/asset_layer/nfts.md'
        - 'sql/tables/canto/asset_layer/collections.md'
        - 'sql/tables/canto/asset_layer/nft_owners.md'
        - 'sql/tables/canto/asset_layer/nft_transfers.md'
        - 'sql/tables/canto/asset_layer/native_token_owners.md'
        - 'sql/tables/canto/asset_layer/native_token_transfers.md'
        - 'sql/tables/canto/asset_layer/tokens.md'
        - 'sql/tables/canto/asset_layer/token_owners.md'
        - 'sql/tables/canto/asset_layer/token_transfers.md'
      - Protocol:
        - 'sql/tables/canto/protocol_layer/nft_sales.md'
        - 'sql/tables/canto/protocol_layer/token_prices.md'
        - 'sql/tables/canto/protocol_layer/dex_pools.md'
        - 'sql/tables/canto/protocol_layer/dex_swaps.md'
        - 'sql/tables/canto/protocol_layer/bridge_events.md'
    - Goerli Tables:
      - Settlement:
        - 'sql/tables/goerli/settlement_layer/accounts.md'
        - 'sql/tables/goerli/settlement_layer/blocks.md'
        - 'sql/tables/goerli/settlement_layer/logs.md'
        - 'sql/tables/goerli/settlement_layer/traces.md'
        - 'sql/tables/goerli/settlement_layer/transactions.md'
      - Asset:
        - 'sql/tables/goerli/asset_layer/nfts.md'
        - 'sql/tables/goerli/asset_layer/collections.md'
        - 'sql/tables/goerli/asset_layer/nft_owners.md'
        - 'sql/tables/goerli/asset_layer/nft_transfers.md'
        - 'sql/tables/goerli/asset_layer/native_token_owners.md'
        - 'sql/tables/goerli/asset_layer/native_token_transfers.md'
        - 'sql/tables/goerli/asset_layer/tokens.md'
        - 'sql/tables/goerli/asset_layer/token_owners.md'
        - 'sql/tables/goerli/asset_layer/token_transfers.md'
      - Protocol:
        - 'sql/tables/goerli/protocol_layer/nft_sales.md'
    - Scroll Tables:
      - Settlement:
        - 'sql/tables/scroll/settlement_layer/accounts.md'
        - 'sql/tables/scroll/settlement_layer/blocks.md'
        - 'sql/tables/scroll/settlement_layer/logs.md'
        - 'sql/tables/scroll/settlement_layer/traces.md'
        - 'sql/tables/scroll/settlement_layer/transactions.md'
      - Asset:
        - 'sql/tables/scroll/asset_layer/nfts.md'
        - 'sql/tables/scroll/asset_layer/collections.md'
        - 'sql/tables/scroll/asset_layer/nft_owners.md'
        - 'sql/tables/scroll/asset_layer/nft_transfers.md'
        - 'sql/tables/scroll/asset_layer/native_token_owners.md'
        - 'sql/tables/scroll/asset_layer/native_token_transfers.md'
        - 'sql/tables/scroll/asset_layer/tokens.md'
        - 'sql/tables/scroll/asset_layer/token_owners.md'
        - 'sql/tables/scroll/asset_layer/token_transfers.md'
      - Protocol:
        - 'sql/tables/scroll/protocol_layer/dex_pools.md'
        - 'sql/tables/scroll/protocol_layer/dex_swaps.md'

  - REST API:
    - Overview: 'rest/overview.md'
    - Authentication: 'rest/authentication.md'
    - Pagination: 'rest/pagination.md'
    - Response: 'rest/response.md'
    - 'Block API':
      - Overview: 'rest/block-api/overview.md'
      - 'Models':
        - Account: 'rest/block-api/models/account_model.md'
        - Block: 'rest/block-api/models/block_model.md'
        - Transaction: 'rest/block-api/models/transaction_model.md' 
        - Log: 'rest/block-api/models/log_model.md'
        - Trace: 'rest/block-api/models/trace_model.md'

      - 'Routes':
        - 'rest/block-api/routes/accounts_by_address.md'
        - 'rest/block-api/routes/accounts_by_creator.md'
        - 'rest/block-api/routes/accounts_by_date_created.md'
        - 'rest/block-api/routes/blocks_by_date.md'
        - 'rest/block-api/routes/blocks_by_number.md'
        - 'rest/block-api/routes/transactions_by_account.md'
        - 'rest/block-api/routes/transactions_by_block.md'
        - 'rest/block-api/routes/transactions_by_contract.md'
        - 'rest/block-api/routes/transactions_by_date.md'
        - 'rest/block-api/routes/transactions_by_hash.md'
        - 'rest/block-api/routes/logs_by_block.md'
        - 'rest/block-api/routes/logs_by_transaction.md'
        - 'rest/block-api/routes/traces_by_account.md'
        - 'rest/block-api/routes/traces_by_block.md'
        - 'rest/block-api/routes/traces_by_transaction.md'
        - 'rest/block-api/routes/traces_by_contract.md'
    - 'Token API':
      - Overview: 'rest/token-api/overview.md'
      - 'Models':
        - 'rest/token-api/models/native_token_balance_model.md'
        - 'rest/token-api/models/native_token_transfer_model.md'
        - 'rest/token-api/models/token_model.md'
        - 'rest/token-api/models/token_owner_model.md'
        - 'rest/token-api/models/token_swap_model.md'
        - 'rest/token-api/models/token_transfer_model.md'
        - 'rest/token-api/models/token_with_owner_model.md'
      - 'Routes':
        - 'rest/token-api/routes/native_token_balances_by_account.md'
        - 'rest/token-api/routes/native_token_transfers_by_account.md'
        - 'rest/token-api/routes/native_token_transfers.md'
        - 'rest/token-api/routes/tokens_by_contract_address.md'
        - 'rest/token-api/routes/tokens_by_date_created.md'
        - 'rest/token-api/routes/tokens_by_name.md'
        - 'rest/token-api/routes/tokens_by_owner.md'
        - 'rest/token-api/routes/tokens_by_symbol.md'
        - 'rest/token-api/routes/owners_by_contract_address.md'
        - 'rest/token-api/routes/transfers.md'
        - 'rest/token-api/routes/transfers_by_contract_address.md'
        - 'rest/token-api/routes/transfers_by_account.md'
        - rest/token-api/routes/swaps.md
        - rest/token-api/routes/swaps_by_account.md
        - rest/token-api/routes/swaps_by_contract_address.md
        - rest/token-api/routes/swaps_by_pair.md
    - 'NFT API':
      - Overview: 'rest/nft-api/overview.md'
      - Models:
        - 'rest/nft-api/models/collection_model.md'
        - 'rest/nft-api/models/nft_model.md'
        - 'rest/nft-api/models/nft_owner_model.md'
        - 'rest/nft-api/models/nft_with_owner_model.md'
        - 'rest/nft-api/models/nft_transfer_model.md'
        - 'rest/nft-api/models/nft_sale_model.md'
      - Routes:
        - 'rest/nft-api/routes/collections_by_contract_address.md'
        - 'rest/nft-api/routes/collections_by_date_created.md'
        - 'rest/nft-api/routes/collections_by_name.md'
        - 'rest/nft-api/routes/collections_by_symbol.md'
        - 'rest/nft-api/routes/nfts_by_contract_address.md'
        - 'rest/nft-api/routes/nfts_by_token_id.md'
        - 'rest/nft-api/routes/nfts_by_date_minted.md'
        - 'rest/nft-api/routes/nfts_by_name.md'
        - 'rest/nft-api/routes/nfts_by_owner.md'
        - 'rest/nft-api/routes/owners_by_contract_address.md'
        - 'rest/nft-api/routes/owners_by_token_id.md'
        - 'rest/nft-api/routes/transfers.md'
        - 'rest/nft-api/routes/transfers_by_contract_address.md'
        - 'rest/nft-api/routes/transfers_by_token_id.md'
        - 'rest/nft-api/routes/transfers_by_account.md'
        - 'rest/nft-api/routes/sales.md'
        - 'rest/nft-api/routes/sales_by_contract_address.md'
        - 'rest/nft-api/routes/sales_by_token_id.md'
        - 'rest/nft-api/routes/sales_by_account.md'
    - 'ENS API':
      - Overview: 'rest/ens-api/overview.md'
      - Models:
        - 'rest/ens-api/models/ens_record_model.md'
        - 'rest/ens-api/models/ens_transfer_model.md'
      - Routes:
        - 'rest/ens-api/routes/ens_records_by_account.md'
        - 'rest/ens-api/routes/ens_records_by_date.md'
        - 'rest/ens-api/routes/ens_records_by_name.md'
        - 'rest/ens-api/routes/ens_records_by_owner.md'
        - 'rest/ens-api/routes/ens_records_by_token_id.md'
        - 'rest/ens-api/routes/ens_transfers_by_name.md'
        - 'rest/ens-api/routes/ens_transfers_by_token_id.md'
  - SDK: 'sdk/overview.md'
  - 'billing.md'
extra:
  analytics:
    provider: google
    property: G-NQR64Q1ME1

extra_javascript:
  - js/codefence/codefence.js
  - js/update_key.js
  - js/tracking.js

extra_css:
  - stylesheets/buttons.css
  - stylesheets/codefence.css
  - stylesheets/core-changes.css

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.extra

plugins:
  - macros
  - search
