site_name: Docs 
theme:
  name: material
  palette:
    primary: deep orange
  logo: ./assets/logo-white.png

extra_javascript:
  - js/requests.js

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - attr_list

plugins:
  - macros
  - apicall
  - search
