site_name: Transpose Documentation
theme:
  name: material
  palette:
    primary: white
  logo: ./assets/logo-black.png
  favicon: ./assets/favicon.png

nav:
  - Introduction: 'index.md'
  - 'Quick Start': 'quickstart.md'
  - 'billing.md'
  - 'REST API':
    - Overview: 'rest/overview.md'
    - Authentication: 'rest/authentication.md'
    - Pagination: 'rest/pagination.md'
    - Response: 'rest/response.md'
    - 'Block API':
      - Overview: 'rest/block-api/overview.md'
      - 'Models':
        - Account: 'rest/block-api/models/account_model.md'
        - Block: 'rest/block-api/models/block_model.md'
        - Log: 'rest/block-api/models/log_model.md'
        - Transaction: 'rest/block-api/models/transaction_model.md' 
      - 'Routes':
        - 'rest/block-api/routes/accounts_by_address.md'
        - 'rest/block-api/routes/accounts_by_creator.md'
        - 'rest/block-api/routes/accounts_by_date_created.md'
        - 'rest/block-api/routes/blocks_by_date.md'
        - 'rest/block-api/routes/blocks_by_number.md'
        - 'rest/block-api/routes/transactions_by_account.md'
        - 'rest/block-api/routes/transactions_by_block.md'
        - 'rest/block-api/routes/transactions_by_date.md'
        - 'rest/block-api/routes/transactions_by_hash.md'
    - 'Token API':
      - Overview: 'rest/token-api/overview.md'
      - 'Models':
        - 'rest/token-api/models/native_token_balance_model.md'
        - 'rest/token-api/models/native_token_transfer_model.md'
        - 'rest/token-api/models/token_model.md'
        - 'rest/token-api/models/token_owner_model.md'
        - 'rest/token-api/models/token_swap_model.md'
        - 'rest/token-api/models/token_transfer_model.md'
        - 'rest/token-api/models/token_with_owner_model.md'
      - 'Routes':
        - 'rest/token-api/routes/native_token_balances_by_account.md'
        - 'rest/token-api/routes/native_token_transfers_by_account.md'
        - 'rest/token-api/routes/native_token_transfers.md'
        - 'rest/token-api/routes/tokens_by_contract_address.md'
        - 'rest/token-api/routes/tokens_by_date_created.md'
        - 'rest/token-api/routes/tokens_by_name.md'
        - 'rest/token-api/routes/tokens_by_owner.md'
        - 'rest/token-api/routes/tokens_by_symbol.md'
        - 'rest/token-api/routes/owners_by_contract_address.md'
        - 'rest/token-api/routes/transfers.md'
        - 'rest/token-api/routes/transfers_by_contract_address.md'
        - 'rest/token-api/routes/transfers_by_account.md'
    - 'NFT API':
      - Overview: 'rest/nft-api/overview.md'
      - Models:
        - 'rest/nft-api/models/collection_model.md'
        - 'rest/nft-api/models/nft_model.md'
        - 'rest/nft-api/models/nft_owner_model.md'
        - 'rest/nft-api/models/nft_with_owner_model.md'
        - 'rest/nft-api/models/nft_transfer_model.md'
        - 'rest/nft-api/models/nft_sale_model.md'
      - Routes:
        - 'rest/nft-api/routes/collections_by_contract_address.md'
        - 'rest/nft-api/routes/collections_by_date_created.md'
        - 'rest/nft-api/routes/collections_by_name.md'
        - 'rest/nft-api/routes/collections_by_symbol.md'
        - 'rest/nft-api/routes/nfts_by_contract_address.md'
        - 'rest/nft-api/routes/nfts_by_token_id.md'
        - 'rest/nft-api/routes/nfts_by_date_minted.md'
        - 'rest/nft-api/routes/nfts_by_name.md'
        - 'rest/nft-api/routes/nfts_by_owner.md'
        - 'rest/nft-api/routes/owners_by_contract_address.md'
        - 'rest/nft-api/routes/owners_by_token_id.md'
        - 'rest/nft-api/routes/transfers.md'
        - 'rest/nft-api/routes/transfers_by_contract_address.md'
        - 'rest/nft-api/routes/transfers_by_token_id.md'
        - 'rest/nft-api/routes/transfers_by_account.md'
        - 'rest/nft-api/routes/sales.md'
        - 'rest/nft-api/routes/sales_by_contract_address.md'
        - 'rest/nft-api/routes/sales_by_token_id.md'
        - 'rest/nft-api/routes/sales_by_account.md'
    - 'ENS API':
      - Overview: 'rest/ens-api/overview.md'
      - Models:
        - 'rest/ens-api/models/ens_record_model.md'
        - 'rest/ens-api/models/ens_transfer_model.md'
      - Routes:
        - 'rest/ens-api/routes/ens_records_by_account.md'
        - 'rest/ens-api/routes/ens_records_by_date.md'
        - 'rest/ens-api/routes/ens_records_by_name.md'
        - 'rest/ens-api/routes/ens_records_by_owner.md'
        - 'rest/ens-api/routes/ens_records_by_token_id.md'
        - 'rest/ens-api/routes/ens_transfers_by_name.md'
        - 'rest/ens-api/routes/ens_transfers_by_token_id.md'
  - SQL API:
    - 'sql/overview.md'
    - Getting Started: 'sql/getting-started.md'
    - 'sql/authentication.md'
    - 'sql/playground.md'
    - 'sql/multichain.md'
    - 'sql/response.md'
    - Options:
        - 'sql/options/stringify.md'
        - 'sql/options/timeout.md'
        - 'sql/options/cancel.md'
    - Tables:
      - Settlement:
        - 'sql/tables/settlement-layer/accounts.md'
        - 'sql/tables/settlement-layer/blocks.md'
        - 'sql/tables/settlement-layer/logs.md'
        - 'sql/tables/settlement-layer/traces.md'
        - 'sql/tables/settlement-layer/transactions.md'
      - Asset:
        - 'sql/tables/asset-layer/contract-labels/contract_labels.md'
        - 'sql/tables/asset-layer/collections/collections.md'
        - 'sql/tables/asset-layer/native-token-owners/native_token_owners.md'
        - 'sql/tables/asset-layer/native-token-transfers/native_token_transfers.md'
        - 'sql/tables/asset-layer/nfts/nfts.md'
        - 'sql/tables/asset-layer/nft-owners/nft_owners.md'
        - 'sql/tables/asset-layer/nft-transfers/nft_transfers.md'
        - 'sql/tables/asset-layer/tokens/tokens.md'
        - 'sql/tables/asset-layer/token-owners/token_owners.md'
        - 'sql/tables/asset-layer/token-transfers/token_transfers.md'
      - Protocol:
        - Bridge Events:
          - 'sql/tables/protocol-layer/aggregate-bridge-events/bridge_events.md'
          - Protocol-Specific Bridge Events:
          - 'sql/tables/protocol-layer/bridge-events/wormhole_bridge_events.md'
          - 'sql/tables/protocol-layer/bridge-events/fantom_bridge_events.md'
          - 'sql/tables/protocol-layer/bridge-events/arbitrum_bridge_events.md'
          - 'sql/tables/protocol-layer/bridge-events/axie_bridge_events.md'
          - 'sql/tables/protocol-layer/bridge-events/avalanche_bridge_events.md'
          - 'sql/tables/protocol-layer/bridge-events/rainbow_bridge_events.md'
          - 'sql/tables/protocol-layer/bridge-events/zkswap_bridge_events.md'
          - 'sql/tables/protocol-layer/bridge-events/synapse_bridge_events.md'
          - 'sql/tables/protocol-layer/bridge-events/multichain_bridge_events.md'
          - 'sql/tables/protocol-layer/bridge-events/harmony_bridge_events.md'
          - 'sql/tables/protocol-layer/bridge-events/metis_bridge_events.md'
          - 'sql/tables/protocol-layer/bridge-events/heco_bridge_events.md'
          - 'sql/tables/protocol-layer/bridge-events/across_bridge_events.md'
          - 'sql/tables/protocol-layer/bridge-events/allbridge_bridge_events.md'
          - 'sql/tables/protocol-layer/bridge-events/celer_bridge_events.md'
          - 'sql/tables/protocol-layer/bridge-events/omg_bridge_events.md'
          - 'sql/tables/protocol-layer/bridge-events/stargate_bridge_events.md'
          - 'sql/tables/protocol-layer/bridge-events/starkex_bridge_events.md'
          - 'sql/tables/protocol-layer/bridge-events/optimism_bridge_events.md'
          - 'sql/tables/protocol-layer/bridge-events/sollet_bridge_events.md'
          - 'sql/tables/protocol-layer/bridge-events/fuse_bridge_events.md'
          - 'sql/tables/protocol-layer/bridge-events/optics_bridge_events.md'
          - 'sql/tables/protocol-layer/bridge-events/layer0_bridge_events.md'
          - 'sql/tables/protocol-layer/bridge-events/hop_bridge_events.md'
          - 'sql/tables/protocol-layer/bridge-events/gnosis_bridge_events.md'
          - 'sql/tables/protocol-layer/bridge-events/ren_bridge_events.md'
          - 'sql/tables/protocol-layer/bridge-events/orbit_bridge_events.md'
          - 'sql/tables/protocol-layer/bridge-events/secret_bridge_events.md'
          - 'sql/tables/protocol-layer/bridge-events/starknet_bridge_events.md'
          - 'sql/tables/protocol-layer/bridge-events/gravity_bridge_events.md'
          - 'sql/tables/protocol-layer/bridge-events/zksync_bridge_events.md'
          - 'sql/tables/protocol-layer/bridge-events/polygon_bridge_events.md'
          - 'sql/tables/protocol-layer/bridge-events/loopring_bridge_events.md'
        - DEX Liquidity:
          - 'sql/tables/protocol-layer/aggregate-dex-liquidity/dex_liquidity.md'
        - DEX Pools: 
          - 'sql/tables/protocol-layer/aggregate-dex-pools/dex_pools.md'
        - DEX Swaps:
          - 'sql/tables/protocol-layer/aggregate-dex-swaps/dex_swaps.md'
        - ENS Names and Registries:
          - 'sql/tables/protocol-layer/ens-names/ens_names.md'
          - 'sql/tables/protocol-layer/ens-registries/ens_registries.md'
        - NFT Sales:
          - 'sql/tables/protocol-layer/aggregate-nft-sales/nft_sales.md'
          - Protocol-Specific NFT Sales:
            - 'sql/tables/protocol-layer/nft-sales/0x_nft_sales.md' 
            - 'sql/tables/protocol-layer/nft-sales/blur_nft_sales.md' 
            - 'sql/tables/protocol-layer/nft-sales/cryptokitties_nft_sales.md' 
            - 'sql/tables/protocol-layer/nft-sales/cryptopunks_nft_sales.md' 
            - 'sql/tables/protocol-layer/nft-sales/foundation_nft_sales.md' 
            - 'sql/tables/protocol-layer/nft-sales/knownorigin_nft_sales.md' 
            - 'sql/tables/protocol-layer/nft-sales/looksrare_nft_sales.md' 
            - 'sql/tables/protocol-layer/nft-sales/opensea_nft_sales.md' 
            - 'sql/tables/protocol-layer/nft-sales/rarible_nft_sales.md' 
            - 'sql/tables/protocol-layer/nft-sales/sudoswap_nft_sales.md' 
            - 'sql/tables/protocol-layer/nft-sales/x_nft_sales.md' 
            - 'sql/tables/protocol-layer/nft-sales/x2y2_nft_sales.md'         
        - Tornado Cash Pools and Events:
          - 'sql/tables/protocol-layer/tornado-cash-withdrawals/tornado_cash_withdrawals.md'
          - 'sql/tables/protocol-layer/tornado-cash-deposits/tornado_cash_deposits.md'
          - 'sql/tables/protocol-layer/tornado-cash-pools/tornado_cash_pools.md'
        - Token Prices:
          - 'sql/tables/protocol-layer/token-prices/token_prices.md'

extra:
  analytics:
    provider: google
    property: G-NQR64Q1ME1

extra_javascript:
  - js/codefence/codefence.js
  - js/update_key.js
  - js/tracking.js

extra_css:
  - stylesheets/buttons.css
  - stylesheets/codefence.css
  - stylesheets/core-changes.css

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.extra

plugins:
  - macros
  - apicall
  - search
